import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    isRTL: boolean;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'select_language': 'Select Language',
        'english': 'English',
        'arabic': 'Arabic',
        'apply': 'Apply Selection',
        'home': 'Home',
        'shop': 'Shop',
        'brands': 'Brands',
        'search_placeholder': 'Search for coffee, desserts...',
        'select_branch': 'Select Branch',
        'categories': 'Categories',
        'view_all': 'View All',
        'popular_now': 'Popular Right Now',
        'see_all': 'See All',
        'quick_actions': 'Quick Actions',
        'help_info': 'Help & Info',
        'legal_extras': 'Legal & Extras',
        'contact_us': 'Contact Us',
        'privacy_policy': 'Privacy Policy',
        'terms_service': 'Terms of Service',
        'company_profile': 'See Our Profile',
        'see_profile': 'See Our Profile',
        'menu': 'Menu',
        'hero_slide1_title': 'iGrab Story Cafe',
        'hero_slide1_subtitle': 'First Emirati brand supporting home businesses specializing in artisanal sweets and premium specialty coffee',
        'hero_slide1_btn': 'Discover Our Story',
        'hero_slide2_title': 'Our Heritage',
        'hero_slide2_subtitle': 'Celebrating UAE\'s culture of generosity and hospitality through exceptional flavors',
        'hero_slide2_btn': 'Learn About Us',
        'hero_slide3_title': 'Quality & Excellence',
        'hero_slide3_subtitle': 'Partnering with premium local producers to deliver authentic Emirati experiences',
        'hero_slide3_btn': 'Explore Our Values',
        'how_it_works_title': 'How It Works',
        'step1_title': 'Browse Menu',
        'step1_desc': 'Explore our wide range of coffee, drinks, food and merchandise.',
        'step2_title': 'Add to Cart',
        'step2_desc': 'Select your favorite items and add them to your shopping cart.',
        'step3_title': 'Checkout',
        'step3_desc': 'Securely pay and choose pickup or delivery options.',
        'step4_title': 'Enjoy!',
        'step4_desc': 'Pick up your order or receive it at your doorstep.',
        'newsletter_badge': 'Our Community',
        'newsletter_title': 'Join the Story',
        'newsletter_desc': 'Subscribe to our newsletter for exclusive offers, new product announcements, and coffee brewing tips delivered straight to your inbox.',
        'newsletter_placeholder': 'Your email address',
        'newsletter_btn': 'Subscribe',
        'newsletter_sending': 'Sending...',
        'newsletter_privacy': 'We respect your privacy. Unsubscribe at any time.',
        'facts_title': 'See Our Facts',
        'see_our_items': 'See Our Items',
        'fact1': 'Built on a community-driven business concept.',
        'fact2': 'Proud to be the First Emirati Brand for this concept',
        'fact3': 'Proudly serving our community, with plans to grow.',
        'fact4': 'Supporting 75 families and more',
        'fact5': 'Have more than 15 brands of sweets shops',
        'fact6': 'Made 3 million sales for the families in one year and half',
        'fact7': 'Ready for Events participation',
        'fact8': 'Serving the finest coffee beans from around the world',
        'fact9': 'Any new branch opens new and more families supports',
        'fact10': 'Approved and licensed delivery vehicles available.',
        'our_products': 'Our Products',
        'shop_subtitle': 'Find your favorite coffee and treats',
        'search_products': 'Search for products...',
        'all': 'All',
        'best_selling': 'Best Selling',
        'search_label': 'Search:',
        'brand_label': 'Brand:',
        'no_results': 'No Results Found',
        'no_results_desc': 'We couldn\'t find any products matching your criteria. Try adjusting your filters or search.',
        'clear_filters': 'Clear All Filters',
        'load_more': 'Load More',
        'sort': 'Sort',
        'sort_new': "What's New",
        'sort_price_high': 'Price High to Low',
        'sort_price_low': 'Price Low to High',
        'sort_name_az': 'Name A to Z',
        'sort_name_za': 'Name Z to A',
        'filter_brand': 'Filter by Brand',
        'search_brands': 'Search brands...',
        'apply_filter': 'Apply Filter',
        'failed_products': 'Failed to load products. Please try again.',
        'retry': 'Retry',
        'add_wishlist': 'Add to wishlist',
        'remove_wishlist': 'Remove from wishlist',
        'add_to_cart': 'Add to Cart',
        'in_cart': 'In Cart',
        'failed_product_details': 'Failed to load product details.',
        'product_not_found': 'Product not found',
        'product_load_error_desc': 'We couldn\'t load the product details. Please try again or go back.',
        'go_back': 'Go Back',
        'view_cart': 'View Cart',
        'add_to_basket': 'Add to Basket',
        'whatsapp': 'WhatsApp',
        'copy_link': 'Copy Link',
        'link_copied': 'Link copied to clipboard!',
        'product_details_title': 'Product Details',
        'show_less': 'Show Less',
        'read_full_desc': 'Read Full Description',
        'share_text': 'Check out this product: ',
        'welcome_back': 'Welcome Back!',
        'create_account': 'Create Account',
        'login_subtitle': 'Enter your mobile to continue',
        'signup_subtitle': 'Enter your details to register',
        'full_name': 'Full Name',
        'mobile_number': 'Mobile Number',
        'name_placeholder': 'John Doe',
        'phone_placeholder': '50 123 4567',
        'login_btn': 'Login',
        'signup_btn': 'Sign Up',
        'no_account': 'Don\'t have an account?',
        'has_account': 'Already have an account?',
        'verify_phone': 'Verify Phone',
        'code_sent_to': 'Code sent to',
        'verify_continue': 'Verify & Continue',
        'no_code': 'Didn\'t receive code?',
        'resend_sms': 'Resend SMS',
        'resend_in': 'Resend in',
        'error_name_req': 'Please enter your name',
        'error_phone_req': 'Please enter your mobile number',
        'error_invalid_phone': 'Invalid phone digits',
        'error_invalid_length': 'Invalid length',
        'error_otp_send': 'Failed to send OTP',
        'error_otp_invalid': 'Invalid OTP',
        'login_failed': 'Login failed',
        'update_failed': 'Update failed',
        'cart_title': 'Your Cart',
        'item': 'item',
        'items': 'items',
        'cart_empty': 'Your cart is empty',
        'cart_empty_desc': 'Add some items to get started',
        'start_shopping': 'Start Shopping',
        'subtotal': 'Subtotal',
        'delivery_calc': 'Delivery charges calculated at checkout',
        'proceed_checkout': 'Proceed to Checkout',
        'wishlist_title': 'Your Wishlist',
        'wishlist': 'Wishlist',
        'item_saved': 'item saved',
        'items_saved': 'items saved',
        'wishlist_empty': 'Your wishlist is empty',
        'wishlist_empty_desc': 'Save items you love for later',
        'browse_products': 'Browse Products',
        'in_cart_tick': '✓ In Cart',
        'move_all_to_cart': 'Move All to Cart',
        'guest_user': 'Guest User',
        'login_track': 'Log in to track orders',
        'login_signup_btn': 'Login / Sign Up',
        'access_saved': 'Access your saved items & orders',
        'recent_orders': 'Recent Orders',
        'orders_loaded': 'loaded',
        'order_id': 'Order ID',
        'no_orders': 'No orders found',
        'view_more_orders': 'View More Orders',
        'support': 'Support',
        'contact_support': 'Contact & Support',
        'edit_profile': 'Edit Profile',
        'my_addresses': 'My Addresses',
        'settings': 'Settings',
        'logout': 'Logout',
        'profile': 'Profile',
        'items_label': 'Items',
        'payment_status': 'Payment Status',
        'download_receipt': 'Download Receipt',
        'paid': 'Paid',
        'unpaid': 'Unpaid',
        'status_delivered': 'Delivered',
        'status_cancelled': 'Cancelled',
        'status_pending': 'Pending',
        'checkout_title': 'Checkout',
        'checkout_subtitle': 'Secure delivery to your doorstep',
        'delivery_details': 'Delivery Details',
        'delivery_location': 'Delivery Location',
        'payment_method': 'Payment Method',
        'cash_on_delivery': 'Cash on Delivery',
        'pay_on_receive': 'Pay when you receive',
        'credit_debit_card': 'Credit / Debit Card',
        'secure_online_payment': 'Secure online payment',
        'order_summary': 'Order Summary',
        'qty_label': 'Qty:',
        'place_order': 'Place Order',
        'pay_securely': 'Pay Securely',
        'order_confirmed': 'Order Confirmed!',
        'order_success_desc': 'Thank you for your order. We\'ll start preparing it right away.',
        'return_home': 'Return Home',
        'error_fill_fields': 'Please fill all required fields and select a location',
        'error_place_order': 'Failed to place order',
        'secure_checkout': 'Secure Checkout',
        'secure_data_desc': 'Your data is always protected with us.',
        'select_location_map': 'Click to select location on map',
        'requires_gmaps': 'Requires Google Maps',
        'map_title': 'Select Delivery Location',
        'map_search_placeholder': 'Search for building, area or street...',
        'loading_maps': 'Loading Maps...',
        'validating_location': 'Validating location...',
        'locating': 'Locating...',
        'selecting': 'Selecting...',
        'confirm_location': 'Confirm Location',
        'checking': 'Checking...',
        'delivery_address': 'Delivery Address',
        'delivery_unavailable_in': 'Delivery currently unavailable in ',
        'please_select_in': 'Please select a location in: ',
        'delivery_not_available_btn': 'Delivery Not Available',
        'contact_page_title': 'Contact Us',
        'contact_subtitle': 'We\'d love to hear from you. Reach out to us with any questions or feedback.',
        'visit_store': 'Visit Our Store',
        'store_address_label': 'Store Address',
        'store_address_val': 'Igrab Story Cafe, Muwileh University Road, Al Mansoor Building, Shop Number 18.',
        'copy_address': 'Copy Address',
        'opening_hours': 'Opening Hours',
        'opening_hours_val': 'Sunday - Saturday: 2:00 PM - 2:00 AM',
        'for_orders_inquiries': 'For orders and inquiries',
        'respond_24h': 'We aim to respond within 24 hours',
        'connect_us': 'Connect With Us',
        'social_desc': 'Follow us for daily updates, special promotions, and coffee inspiration!',
        'find_us': 'Find Us',
        'send_message_title': 'Send Us a Message',
        'your_name_label': 'Your Name',
        'your_email_label': 'Your Email',
        'your_phone_label': 'Your Phone',
        'inquiry_type': 'Inquiry Type',
        'general_inquiry': 'General Inquiry',
        'order_issue': 'Order Issue',
        'business_inquiry': 'Business Inquiry',
        'message_label': 'Message',
        'message_placeholder': 'Tell us how we can help you',
        'sending': 'Sending...',
        'send_message_btn': 'Send Message',
        'contact_success': 'Your message has been sent successfully!',
        'contact_error': 'Failed to send message. Please try again.',
        'address_copied': 'Address copied to clipboard!',
        'stay_connected': 'Stay Connected',
        'newsletter_success': 'Thank you for subscribing!',
        'newsletter_error': 'Subscription failed. Please try again.',
        'legal_doc': 'Legal Documentation',
        'privacy_title': 'Privacy Policy',
        'last_updated': 'Last updated: March 03, 2026',
        'privacy_welcome': 'Welcome to iGrab Story Cafe. Your privacy is paramount to us. This Privacy Policy outlines how we collect, use, disclose, and safeguard your information when you use our mobile application or website, particularly focusing on our services in the United Arab Emirates.',
        'info_collect_title': 'Information We Collect',
        'info_collect_desc': 'We collect information that allows us to provide a seamless coffee and food delivery experience:',
        'personal_data_label': 'Personal Data:',
        'personal_data_val': 'Name, email address, and phone number provided during registration.',
        'delivery_info_label': 'Delivery Info:',
        'delivery_info_val': 'Physical addresses and precise location data (via GPS) to ensure accurate delivery.',
        'transaction_data_label': 'Transaction Data:',
        'transaction_data_val': 'Details of orders you place and payment method preferences (we do not store full credit card details).',
        'device_info_label': 'Device Info:',
        'device_info_val': 'IP address, device type, and operating system version for app optimization.',
        'how_we_use_title': 'How We Use Your Information',
        'how_we_use_desc': 'Your data enables us to:',
        'how_we_use_point1': 'Process, fulfill, and deliver your orders from our branches.',
        'how_we_use_point2': 'Send order updates and customer support communications.',
        'how_we_use_point3': 'Analyze app performance to fix bugs and improve user interface.',
        'how_we_use_point4': 'Comply with local UAE regulations regarding food safety and commercial transactions.',
        'data_sharing_title': 'Data Sharing & Security',
        'data_sharing_desc': 'We do not sell your personal information. We only share data with:',
        'payment_processors_label': 'Payment Processors:',
        'payment_processors_val': 'Secure services like Stripe to handle transactions.',
        'delivery_partners_label': 'Delivery Partners:',
        'delivery_partners_val': 'To get your coffee and food to your doorstep.',
        'security_note': 'We use industry-standard encryption and secure servers to protect your data from unauthorized access.',
        'rights_title': 'Your Rights (Account Deletion)',
        'rights_desc': 'In compliance with App Store and Google Play policies, you have the right to:',
        'rights_point1': 'Access, update, or correct your personal information in your profile.',
        'rights_point2': 'Request account deletion: You can request to delete your account and all associated data by contacting us at the email below.',
        'legal_address_val': 'Muwileh University Road, Sharjah, UAE',
        'terms_title': 'Terms & Conditions',
        'terms_welcome': 'These Terms & Conditions (“Terms”) govern your use of the iGrab Story Cafe mobile application and services. By accessing our platform, you agree to be bound by these Terms.',
        'eligibility_title': 'Eligibility & Accounts',
        'eligibility_desc': 'By using iGrab, you confirm that you are at least 18 years old or using the platform under parental supervision. You are responsible for maintaining the confidentiality of your account and password.',
        'orders_payments_title': 'Orders & Payments',
        'orders_payments_desc': 'All orders are subject to availability. Prices are listed in AED and include applicable taxes unless stated otherwise.',
        'payments_point_label': 'Payments:',
        'payments_point_val': 'We accept online payments via Stripe and Cash on Delivery (COD).',
        'cancellations_point_label': 'Cancellations:',
        'cancellations_point_val': 'Orders can be cancelled before they are prepared. Once preparation begins, cancellations may not be eligible for a refund.',
        'delivery_terms_title': 'Delivery Terms',
        'delivery_terms_desc': 'Delivery times are estimates. We strive for punctuality but are not liable for delays caused by traffic, weather, or third-party factors.',
        'delivery_point1': 'Customers must provide an accurate delivery address and be available to receive the order.',
        'delivery_point2': 'Unsuccessful delivery attempts due to customer unavailability may still be charged in full.',
        'refund_policy_title': 'Refund & Quality Policy',
        'refund_policy_desc': 'Due to the perishable nature of our products, refunds are only issued for:',
        'refund_point1': 'Incorrect items delivered.',
        'refund_point2': 'Items damaged during delivery.',
        'report_issue_note': 'Please report any issues within 30 minutes of delivery to be eligible for review.',
        'intellectual_property_title': 'Intellectual Property',
        'intellectual_property_desc': 'All content on the iGrab platform, including logos, designs, and text, is the exclusive property of iGrab Story Cafe. Unauthorized reproduction or use is strictly prohibited.',
        'governing_law_title': 'Governing Law',
        'governing_law_desc': 'These terms are governed by the laws of the United Arab Emirates. Any disputes will be subject to the exclusive jurisdiction of the UAE courts.',
        'need_help_title': 'Need Help?',
        'need_help_desc': 'If you have any questions about these Terms, please reach out to our team.',
        '404_title': 'Page Not Found',
        '404_desc': 'The coffee you\'re looking for might have been moved or doesn\'t exist. Let\'s get you back to the menu.',
        'back_to_home': 'Back to Home',
        'browse_menu': 'Browse Menu',
        'profile_hero_title': 'Our Company Profile',
        'profile_hero_desc': 'Discover the story, mission, and the passion behind iGrab Story Cafe.',
        'profile_established': 'Established 2016',
        'profile_identity': 'Identity',
        'who_we_are': 'Who We Are?',
        'who_we_are_p1': 'Located in Sharjah, UAE, iGrab Story Cafe is a unique hub for high-quality food, specialty coffee, and homemade products. Our menu features a variety of sweets, beverages, and coffee, including Arabic sweets and ice cream.',
        'profile_our_story': 'Our Story',
        'our_story_p1': 'Our story began in 2016 when the demand for home-based businesses was rising, yet timely service and delivery were lacking. These businesses also needed support in marketing, presentation, and distribution.',
        'our_story_p2': 'This sparked an idea—why not bring them all together in one place? iGrab Story Café was founded by Mr. Fahad Al Shehhi, who aspired to deliver unique and authentic Emirati offerings from over 30 family-run enterprises.',
        'profile_mission': 'Our Mission',
        'mission_desc': 'To satisfy the passion of our customers by providing them with premium food and beverage options, going beyond the ordinary.',
        'profile_vision': 'Our Vision',
        'vision_desc': 'Rooted in the art of \'Giving,\' we aim to empower homemade businesses by providing a thriving platform for quality, innovation, and community growth.',
        'profile_values_title': 'Our Core Values',
        'profile_values_desc': 'Commitment to delivering an exceptional experience through perfection and joy.',
        'value_perfection': 'Perfection',
        'value_perfection_desc': 'Believing in perfection while serving guests, starting from every single detail.',
        'value_joy': 'Joy',
        'value_joy_desc': 'Our main theme is to create a joyful experience which is at our very root.',
        'value_growth': 'Growth',
        'value_growth_desc': 'Our staff is keen to grow and expand their expertise through daily learning.',
        'value_experience': 'Experience',
        'value_experience_desc': 'Willingness to provide tremendous service experiences for all our guests.',
        'profile_meaning_title': 'The Meaning of iGrab',
        'profile_meaning_p1': 'In UAE local culture, \'iGrab\' is an invitation of pure hospitality. It describes individuals who follow the principle of giving and serving others straight from the heart, without seeking anything in return.',
        'profile_meaning_p2': 'The idea of iGrab Story Cafe is genuinely inspired by the kindness and generosity practiced in Emirati culture, where sharing a meal is a blessing and a way to connect with neighbors.',
        'art_of_giving': 'Art of Giving',
        'brands_title': 'Brands We Partner With',
        'brands_subtitle': 'Collaborating with the finest local and international partners to ensure excellence.',
        'active_partners': 'Active Partners'
    },
    ar: {
        'select_language': 'اختر اللغة',
        'english': 'الإنجليزية',
        'arabic': 'العربية',
        'apply': 'تطبيق الاختيار',
        'home': 'الرئيسية',
        'shop': 'المتجر',
        'brands': 'العلامات التجارية',
        'search_placeholder': 'ابحث عن القهوة، الحلويات...',
        'select_branch': 'اختر الفرع',
        'categories': 'الفئات',
        'view_all': 'عرض الكل',
        'popular_now': 'الأكثر طلباً الآن',
        'see_all': 'مشاهدة الكل',
        'quick_actions': 'إجراءات سريعة',
        'help_info': 'المساعدة والمعلومات',
        'legal_extras': 'قانوني وإضافات',
        'contact_us': 'صل بنا',
        'privacy_policy': 'سياسة الخصوصية',
        'terms_service': 'شروط الخدمة',
        'company_profile': 'ملف الشركة',
        'see_profile': 'ملف الشركة',
        'menu': 'القائمة',
        'hero_slide1_title': 'آي جراب ستوري كافيه',
        'hero_slide1_subtitle': 'أول علامة تجارية إماراتية تدعم المشاريع المنزلية المتخصصة في الحلويات الحرفية والقهوة المختصة الفاخرة',
        'hero_slide1_btn': 'اكتشف قصتنا',
        'hero_slide2_title': 'تراثنا',
        'hero_slide2_subtitle': 'نحتفي بثقافة الكرم والضيافة الإماراتية من خلال نكهات استثنائية',
        'hero_slide2_btn': 'تعرف علينا',
        'hero_slide3_title': 'الجودة والتميز',
        'hero_slide3_subtitle': 'شراكة مع منتجين محليين متميزين لتقديم تجارب إماراتية أصيلة',
        'hero_slide3_btn': 'استكشف قيمنا',
        'how_it_works_title': 'كيف نعمل',
        'step1_title': 'تصفح القائمة',
        'step1_desc': 'استكشف مجموعتنا الواسعة من القهوة والمشروبات والطعام والسلع.',
        'step2_title': 'أضف إلى السلة',
        'step2_desc': 'اختر منتجاتك المفضلة وأضفها إلى سلة التسوق الخاصة بك.',
        'step3_title': 'الدفع',
        'step3_desc': 'ادفع بأمان واختر خيارات الاستلام أو التوصيل.',
        'step4_title': 'استمتع!',
        'step4_desc': 'استلم طلبك أو استلمه عند باب منزلك.',
        'newsletter_badge': 'مجتمعنا',
        'newsletter_title': 'انضم إلى القصة',
        'newsletter_desc': 'اشترك في نشرتنا الإخبارية للحصول على عروض حصرية، وإعلانات عن منتجات جديدة، ونصائح تحضير القهوة مباشرة إلى بريدك الوارد.',
        'newsletter_placeholder': 'بريدك الإلكتروني',
        'newsletter_btn': 'اشترك',
        'newsletter_sending': 'جاري الإرسال...',
        'newsletter_privacy': 'نحن نحترم خصوصيتك. يمكنك إلغاء الاشتراك في أي وقت.',
        'facts_title': 'حقائق عنا',
        'see_our_items': 'تصفح منتجاتنا',
        'fact1': 'مبنية على مفهوم عمل مجتمعي.',
        'fact2': 'فخورون بكوننا أول علامة تجارية إماراتية بهذا المفهوم',
        'fact3': 'فخورون بخدمة مجتمعنا، مع خطط للنمو.',
        'fact4': 'دعم 75 أسرة وأكثر',
        'fact5': 'نملك أكثر من 15 علامة تجارية لمحلات الحلويات',
        'fact6': 'حققنا مبيعات بقيمة 3 ملايين للأسر في عام ونصف',
        'fact7': 'جاهزون للمشاركة في الفعاليات',
        'fact8': 'نقدم أجود أنواع حبوب القهوة من جميع أنحاء العالم',
        'fact9': 'كل فرع جديد يفتح آفاقاً لدعم المزيد من الأسر',
        'fact10': 'تتوفر مركبات توصيل معتمدة ومرخصة.',
        'our_products': 'منتجاتنا',
        'shop_subtitle': 'اكتشف القهوة والحلويات المفضلة لديك',
        'search_products': 'ابحث عن المنتجات...',
        'all': 'الكل',
        'best_selling': 'الأكثر مبيعاً',
        'search_label': 'البحث:',
        'brand_label': 'العلامة التجارية:',
        'no_results': 'لم يتم العثور على نتائج',
        'no_results_desc': 'لم نتمكن من العثور على أي منتجات تطابق معاييرك. حاول تعديل الفلاتر أو البحث.',
        'clear_filters': 'مسح الكل',
        'load_more': 'تحميل المزيد',
        'sort': 'ترتيب',
        'sort_new': 'ما الجديد',
        'sort_price_high': 'السعر: من الأعلى إلى الأقل',
        'sort_price_low': 'السعر: من الأقل إلى الأعلى',
        'sort_name_az': 'الاسم: من أ إلى ي',
        'sort_name_za': 'الاسم: من ي إلى أ',
        'filter_brand': 'تصفية حسب العلامة التجارية',
        'search_brands': 'البحث عن العلامات التجارية...',
        'apply_filter': 'تطبيق التصفية',
        'failed_products': 'فشل تحميل المنتجات. يرجى المحاولة مرة أخرى.',
        'retry': 'إعادة المحاولة',
        'add_wishlist': 'إضافة إلى المفضلة',
        'remove_wishlist': 'إزالة من المفضلة',
        'add_to_cart': 'أضف إلى السلة',
        'in_cart': 'في السلة',
        'failed_product_details': 'فشل تحميل تفاصيل المنتج.',
        'product_not_found': 'المنتج غير موجود',
        'product_load_error_desc': 'لم نتمكن من تحميل تفاصيل المنتج. يرجى المحاولة مرة أخرى أو العودة.',
        'go_back': 'العودة',
        'view_cart': 'عرض السلة',
        'add_to_basket': 'أضف إلى السلة',
        'whatsapp': 'واتساب',
        'copy_link': 'نسخ الرابط',
        'link_copied': 'تم نسخ الرابط إلى الحافظة!',
        'product_details_title': 'تفاصيل المنتج',
        'show_less': 'عرض أقل',
        'read_full_desc': 'اقرأ الوصف الكامل',
        'share_text': 'شاهد هذا المنتج: ',
        'welcome_back': 'مرحباً بعودتك!',
        'create_account': 'إنشاء حساب',
        'login_subtitle': 'أدخل رقم هاتفك للمتابعة',
        'signup_subtitle': 'أدخل بياناتك للتسجيل',
        'full_name': 'الاسم الكامل',
        'mobile_number': 'رقم الهاتف المتحرك',
        'name_placeholder': 'فلان الفلاني',
        'phone_placeholder': '50 123 4567',
        'login_btn': 'تسجيل الدخول',
        'signup_btn': 'إنشاء حساب',
        'no_account': 'ليس لديك حساب؟',
        'has_account': 'لديك حساب بالفعل؟',
        'verify_phone': 'التحقق من الهاتف',
        'code_sent_to': 'تم إرسال الرمز إلى',
        'verify_continue': 'التحقق والمتابعة',
        'no_code': 'لم تستلم الرمز؟',
        'resend_sms': 'إعادة إرسال الرمز',
        'resend_in': 'إعادة الإرسال خلال',
        'error_name_req': 'يرجى إدخال الاسم',
        'error_phone_req': 'يرجى إدخال رقم الهاتف',
        'error_invalid_phone': 'أرقام الهاتف غير صالحة',
        'error_invalid_length': 'طول الرقم غير صالح',
        'error_otp_send': 'فشل إرسال الرمز',
        'error_otp_invalid': 'الرمز غير صالح',
        'login_failed': 'فشل تسجيل الدخول',
        'update_failed': 'فشل التحديث',
        'cart_title': 'سلة التسوق',
        'item': 'منتج',
        'items': 'منتجات',
        'cart_empty': 'سلتك فارغة',
        'cart_empty_desc': 'أضف بعض المنتجات للبدء',
        'start_shopping': 'ابدأ التسوق',
        'subtotal': 'المجموع الفرعي',
        'delivery_calc': 'يتم حساب رسوم التوصيل عند الدفع',
        'proceed_checkout': 'المتابعة لإتمام الطلب',
        'wishlist_title': 'قائمة الأمنيات',
        'wishlist': 'المفضلة',
        'item_saved': 'منتج محفوظ',
        'items_saved': 'منتجات محفوظة',
        'wishlist_empty': 'قائمة الأمنيات فارغة',
        'wishlist_empty_desc': 'احفظ المنتجات التي تحبها لوقت لاحق',
        'browse_products': 'تصفح المنتجات',
        'in_cart_tick': '✓ في السلة',
        'move_all_to_cart': 'نقل الكل إلى السلة',
        'guest_user': 'مستخدم زائر',
        'login_track': 'سجل الدخول لتتبع طلباتك',
        'login_signup_btn': 'الدخول / الاشتراك',
        'access_saved': 'الوصول إلى منتجاتك المحفوظة وطلباتك',
        'recent_orders': 'الطلبات الأخيرة',
        'orders_loaded': 'تم تحميلها',
        'order_id': 'رقم الطلب',
        'no_orders': 'لا توجد طلبات',
        'view_more_orders': 'عرض المزيد من الطلبات',
        'support': 'الدعم',
        'contact_support': 'التواصل والدعم',
        'edit_profile': 'تعديل الملف الشخصي',
        'my_addresses': 'عناويني',
        'settings': 'الإعدادات',
        'logout': 'تسجيل الخروج',
        'profile': 'الملف الشخصي',
        'items_label': 'المنتجات',
        'payment_status': 'حالة الدفع',
        'download_receipt': 'تحميل الإيصال',
        'paid': 'تم الدفع',
        'unpaid': 'لم يتم الدفع',
        'status_delivered': 'تم التوصيل',
        'status_cancelled': 'ملغي',
        'status_pending': 'قيد الانتظار',
        'checkout_title': 'إتمام الطلب',
        'checkout_subtitle': 'توصيل آمن إلى باب منزلك',
        'delivery_details': 'تفاصيل التوصيل',
        'delivery_location': 'موقع التوصيل',
        'payment_method': 'طريقة الدفع',
        'cash_on_delivery': 'الدفع عند الاستلام',
        'pay_on_receive': 'ادفع عند الاستلام',
        'credit_debit_card': 'بطاقة ائتمان / خصم',
        'secure_online_payment': 'دفع آمن عبر الإنترنت',
        'order_summary': 'ملخص الطلب',
        'qty_label': 'الكمية:',
        'place_order': 'إتمام الطلب',
        'pay_securely': 'دفع آمن',
        'order_confirmed': 'تم تأكيد الطلب!',
        'order_success_desc': 'شكراً لطلبك. سنبدأ في تجهيزه على الفور.',
        'return_home': 'العودة للرئيسية',
        'error_fill_fields': 'يرجى ملء جميع الحقول المطلوبة واختيار الموقع',
        'error_place_order': 'فشل في إتمام الطلب',
        'secure_checkout': 'دفع آمن',
        'secure_data_desc': 'بياناتك محمية دائماً معنا.',
        'select_location_map': 'انقر لاختيار الموقع على الخريطة',
        'requires_gmaps': 'يتطلب خرائط جوجل',
        'map_title': 'اختر موقع التوصيل',
        'map_search_placeholder': 'ابحث عن مبنى، منطقة أو شارع...',
        'loading_maps': 'جاري تحميل الخرائط...',
        'validating_location': 'جاري التحقق من الموقع...',
        'locating': 'جاري تحديد الموقع...',
        'selecting': 'جاري الاختيار...',
        'confirm_location': 'تأكيد الموقع',
        'checking': 'جاري الفحص...',
        'delivery_address': 'عنوان التوصيل',
        'delivery_unavailable_in': 'التوصيل غير متاح حالياً في ',
        'please_select_in': 'يرجى اختيار موقع في: ',
        'delivery_not_available_btn': 'التوصيل غير متاح',
        'contact_page_title': 'اتصل بنا',
        'contact_subtitle': 'يسعدنا سماع رأيك. تواصل معنا لأي استفسارات أو ملاحظات.',
        'visit_store': 'قم بزيارة متجرنا',
        'store_address_label': 'عنوان المتجر',
        'store_address_val': 'آي جراب ستوري كافيه، طريق مويلح الجامعي، بناية المنصور، محل رقم 18.',
        'copy_address': 'نسخ العنوان',
        'opening_hours': 'ساعات العمل',
        'opening_hours_val': 'الأحد - السبت: 2:00 ظهراً - 2:00 صباحاً',
        'for_orders_inquiries': 'للطلبات والاستفسارات',
        'respond_24h': 'نهدف للرد خلال 24 ساعة',
        'connect_us': 'تواصل معنا',
        'social_desc': 'تابعنا للحصول على التحديثات اليومية، العروض الترويجية الخاصة، وإلهام القهوة!',
        'find_us': 'تجدنا هنا',
        'send_message_title': 'أرسل لنا رسالة',
        'your_name_label': 'اسمك',
        'your_email_label': 'بريدك الإلكتروني',
        'your_phone_label': 'هاتفك',
        'inquiry_type': 'نوع الاستفسار',
        'general_inquiry': 'استفسار عام',
        'order_issue': 'مشكلة في الطلب',
        'business_inquiry': 'استفسار تجاري',
        'message_label': 'الرسالة',
        'message_placeholder': 'أخبرنا كيف يمكننا مساعدتك',
        'sending': 'جاري الإرسال...',
        'send_message_btn': 'إرسال الرسالة',
        'contact_success': 'تم إرسال رسالتك بنجاح!',
        'contact_error': 'فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.',
        'address_copied': 'تم نسخ العنوان!',
        'stay_connected': 'ابق على اتصال',
        'newsletter_success': 'شكراً لاشتراكك!',
        'newsletter_error': 'فشل الاشتراك. يرجى المحاولة مرة أخرى.',
        'legal_doc': 'وثائق قانونية',
        'privacy_title': 'سياسة الخصوصية',
        'last_updated': 'آخر تحديث: 3 مارس 2026',
        'privacy_welcome': 'أهلاً بكم في آي جراب ستوري كافيه. خصوصيتكم تهمنا للغاية. توضح سياسة الخصوصية هذه كيفية جمع معلوماتكم واستخدامها والإفصاح عنها وحمايتها عند استخدام تطبيقنا أو موقعنا الإلكتروني، مع التركيز بشكل خاص على خدماتنا في دولة الإمارات العربية المتحدة.',
        'info_collect_title': 'المعلومات التي نجمعها',
        'info_collect_desc': 'نحن نجمع المعلومات التي تتيح لنا تقديم تجربة سلسة لتوصيل القهوة والطعام:',
        'personal_data_label': 'البيانات الشخصية:',
        'personal_data_val': 'الاسم، عنوان البريد الإلكتروني، ورقم الهاتف المقدم عند التسجيل.',
        'delivery_info_label': 'معلومات التوصيل:',
        'delivery_info_val': 'العناوين الفعلية وبيانات الموقع الدقيقة (عبر نظام تحديد المواقع العالمي GPS) لضمان تسليم دقيق.',
        'transaction_data_label': 'بيانات المعاملات:',
        'transaction_data_val': 'تفاصيل الطلبات التي تجريها وتفضيلات طريقة الدفع (نحن لا نخزن تفاصيل بطاقة الائتمان الكاملة).',
        'device_info_label': 'معلومات الجهاز:',
        'device_info_val': 'عنوان IP، نوع الجهاز، وإصدار نظام التشغيل لتحسين التطبيق.',
        'how_we_use_title': 'كيف نستخدم معلوماتك',
        'how_we_use_desc': 'بياناتك تتيح لنا:',
        'how_we_use_point1': 'معالجة وتنفيذ وتسليم طلباتك من فروعنا.',
        'how_we_use_point2': 'إرسال تحديثات الطلبات واتصالات دعم العملاء.',
        'how_we_use_point3': 'تحليل أداء التطبيق لإصلاح الأخطاء وتحسين واجهة المستخدم.',
        'how_we_use_point4': 'الامتثال للوائح المحلية في دولة الإمارات العربية المتحدة فيما يتعلق بسلامة الأغذية والمعاملات التجارية.',
        'data_sharing_title': 'مشاركة البيانات وأمنها',
        'data_sharing_desc': 'نحن لا نبيع معلوماتك الشخصية. نحن نشارك البيانات فقط مع:',
        'payment_processors_label': 'معالجي الدفع:',
        'payment_processors_val': 'خدمات آمنة مثل Stripe للتعامل مع المعاملات.',
        'delivery_partners_label': 'شركاء التوصيل:',
        'delivery_partners_val': 'لتوصيل القهوة والطعام إلى باب منزلك.',
        'security_note': 'نحن نستخدم تشفيراً بمعايير الصناعة وخوادم آمنة لحماية بياناتك من الوصول غير المصرح به.',
        'rights_title': 'حقوقك (حذف الحساب)',
        'rights_desc': 'امتثالاً لسياسات متجر التطبيقات وGoogle Play، يحق لك:',
        'rights_point1': 'الوصول إلى معلوماتك الشخصية في ملفك الشخصي أو تحديثها أو تصحيحها.',
        'rights_point2': 'طلب حذف الحساب: يمكنك طلب حذف حسابك وجميع البيانات المرتبطة به من خلال الاتصال بنا عبر البريد الإلكتروني أدناه.',
        'legal_address_val': 'طريق مويلح الجامعي، الشارقة، الإمارات العربية المتحدة',
        'terms_title': 'الشروط والأحكام',
        'terms_welcome': 'تحكم هذه الشروط والأحكام ("الشروط") استخدامك لتطبيق وخدمات آي جراب ستوري كافيه. من خلال الوصول إلى منصتنا، فإنك توافق على الالتزام بهذه الشروط.',
        'eligibility_title': 'الأهلية والحسابات',
        'eligibility_desc': 'باستخدامك لـ آي جراب، فإنك تؤكد أنك تبلغ من العمر 18 عاماً على الأقل أو تستخدم المنصة تحت إشراف الوالدين. أنت مسؤول عن الحفاظ على سرية حسابك وكلمة مرورك.',
        'orders_payments_title': 'الطلبات والمدفوعات',
        'orders_payments_desc': 'تخضع جميع الطلبات لتوفر المنتجات. الأسعار مدرجة بالدرهم الإماراتي وتشمل الضرائب المعمول بها ما لم ينص على خلاف ذلك.',
        'payments_point_label': 'المدفوعات:',
        'payments_point_val': 'نحن نقبل المدفوعات عبر الإنترنت من خلال Stripe والدفع عند الاستلام (COD).',
        'cancellations_point_label': 'الإلغاء:',
        'cancellations_point_val': 'يمكن إلغاء الطلبات قبل البدء في تحضيرها. بمجرد بدء التحضير، قد لا تكون عمليات الإلغاء مؤهلة لاسترداد الأموال.',
        'delivery_terms_title': 'شروط التوصيل',
        'delivery_terms_desc': 'أوقات التوصيل هي أوقات تقديرية. نحن نسعى جاهدين للالتزام بالمواعيد ولكننا لسنا مسؤولين عن التأخير الناتج عن حركة المرور أو الطقس أو عوامل خارجية.',
        'delivery_point1': 'يجب على العملاء تقديم عنوان توصيل دقيق والتواجد لاستلام الطلب.',
        'delivery_point2': 'قد يتم فرض رسوم كاملة على محاولات التوصيل غير الناجحة بسبب عدم تواجد العميل.',
        'refund_policy_title': 'سياسة الاسترداد والجودة',
        'refund_policy_desc': 'نظراً للطبيعة القابلة للتلف لمنتجاتنا، يتم إصدار مستردات فقط لـ:',
        'refund_point1': 'المنتجات غير الصحيحة التي تم تسليمها.',
        'refund_point2': 'المنتجات التي تضررت أثناء التوصيل.',
        'report_issue_note': 'يرجى الإبلاغ عن أي مشكلات خلال 30 دقيقة من التوصيل لتكون مؤهلة للمراجعة.',
        'intellectual_property_title': 'الملكية الفكرية',
        'intellectual_property_desc': 'جميع محتويات منصة آي جراب، بما في ذلك الشعارات والتصاميم والنصوص، هي ملكية حصرية لـ آي جراب ستوري كافيه. يحظر تماماً إعادة إنتاجها أو استخدامها دون تصريح.',
        'governing_law_title': 'القانون الواجب التطبيق',
        'governing_law_desc': 'تخضع هذه الشروط لقوانين دولة الإمارات العربية المتحدة. وتخضع أي نزاعات للاختصاص القضائي الحصري لمحاكم دولة الإمارات العربية المتحدة.',
        'need_help_title': 'هل تحتاج مساعدة؟',
        'need_help_desc': 'إذا كانت لديك أي أسئلة حول هذه الشروط، يرجى التواصل مع فريقنا.',
        '404_title': 'الصفحة غير موجودة',
        '404_desc': 'القهوة التي تبحث عنها ربما تم نقلها أو أنها غير موجودة. لنعد بك إلى القائمة.',
        'back_to_home': 'العودة للرئيسية',
        'browse_menu': 'تصفح القائمة',
        'profile_hero_title': 'ملف الشركة',
        'profile_hero_desc': 'اكتشف قصة ورسالة وشغف آي جراب ستوري كافيه.',
        'profile_established': 'تأسس عام 2016',
        'profile_identity': 'الهوية',
        'who_we_are': 'من نحن؟',
        'who_we_are_p1': 'يقع آي جراب ستوري كافيه في الشارقة، الإمارات العربية المتحدة، وهو مركز فريد للأطعمة عالية الجودة والقهوة المختصة والمنتجات المنزلية. تضم قائمتنا مجموعة متنوعة من الحلويات والمشروبات والقهوة، بما في ذلك الحلويات العربية والآيس كريم.',
        'profile_our_story': 'قصتنا',
        'our_story_p1': 'بدأت قصتنا في عام 2016 عندما كان الطلب على المشاريع المنزلية في ازدياد، ومع ذلك كانت الخدمة والتوصيل في الوقت المناسب مفقودة. كما احتاجت هذه المشاريع إلى دعم في التسويق والعرض والتوزيع.',
        'our_story_p2': 'أثار هذا فكرة - لماذا لا نجمعهم جميعاً في مكان واحد؟ تأسس آي جراب ستوري كافيه من قبل السيد فهد الشحي، الذي طمح لتقديم عروض إماراتية فريدة وأصيلة من أكثر من 30 مؤسسة تديرها عائلات.',
        'profile_mission': 'رسالتنا',
        'mission_desc': 'إشباع شغف عملائنا من خلال تزويدهم بخيارات أطعمة ومشروبات متميزة، تتجاوز المألوف.',
        'profile_vision': 'رؤيتنا',
        'vision_desc': 'متجذرون في فن "العطاء"، نهدف إلى تمكين المشاريع المنزلية من خلال توفير منصة مزدهرة للجودة والابتكار ونمو المجتمع.',
        'profile_values_title': 'قيمنا الأساسية',
        'profile_values_desc': 'الالتزام بتقديم تجربة استثنائية من خلال الإتقان والبهجة.',
        'value_perfection': 'الإتقان',
        'value_perfection_desc': 'الإيمان بالإتقان أثناء خدمة الضيوف، بدءاً من كل تفصيل صغير.',
        'value_joy': 'البهجة',
        'value_joy_desc': 'موضوعنا الرئيسي هو خلق تجربة مبهجة هي أصلنا وجذرنا.',
        'value_growth': 'النمو',
        'value_growth_desc': 'موظفونا حرصاء على النمو وتوسيع خبراتهم من خلال التعلم اليومي.',
        'value_experience': 'الخبرة',
        'value_experience_desc': 'الاستعداد لتقديم تجارب خدمية هائلة لجميع ضيوفنا.',
        'profile_meaning_title': 'معنى آي جراب',
        'profile_meaning_p1': 'في الثقافة المحلية لدولة الإمارات العربية المتحدة، "آي جراب" هي دعوة للضيافة الخالصة. وهي تصف الأفراد الذين يتبعون مبدأ العطاء وخدمة الآخرين من القلب مباشرة، دون طلب أي شيء في المقابل.',
        'profile_meaning_p2': 'إن فكرة آي جراب ستوري كافيه مستوحاة بصدق من اللطف والكرم الممارس في الثقافة الإماراتية، حيث تفتح مشاركة الوجبة باباً للبركة ووسيلة للتواصل مع الجيران.',
        'art_of_giving': 'فن العطاء',
        'brands_title': 'العلامات التجارية الشريكة',
        'brands_subtitle': 'التعاون مع أرقى الشركاء المحليين والدوليين لضمان التميز.',
        'active_partners': 'شركاء نشطون'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('app_language');
        return (saved === 'ar' || saved === 'en') ? saved : 'en';
    });

    const isRTL = language === 'ar';

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);
    };

    useEffect(() => {
        document.documentElement.lang = language;
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';

        // Add/remove RTL class to body for global CSS targeting
        if (isRTL) {
            document.body.classList.add('rtl');
        } else {
            document.body.classList.remove('rtl');
        }
    }, [language, isRTL]);

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
